version: '3'

services:
  journeys-db:
    container_name: journeys-db
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dlamas
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=journeys
  redis:
      container_name: redis
      image: redis:latest
      restart: always
      ports:
        - 6379:6379
      volumes:
        - redis-data:/data
        
volumes:
  redis-data: